# Generated by Django 4.2.14 on 2024-08-07 04:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='people_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='people_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='took',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=21), blank=True, null=True, size=None),
        ),
    ]
