# Generated by Django 4.2.14 on 2024-08-07 20:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_commentary_people_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='took',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=21), size=None),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_us', to=settings.AUTH_USER_MODEL)),
                ('relate_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relate_us', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
